spring:
  application:
    name: feedback-analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

feedback:
  batch:
    chunk-size: 1
    sleep-duration: 15000

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: gemini-2.5-flash
      temperature: 0.2
      log-requests-and-responses: true


